import matplotlib.pyplot as plt
import pandas as pd

import sp
import vis

def plot_all():
    hrv = pd.read_pickle('dfs/hrv.pkl') # hrv.pickle is generated by parse_data.py
    hrv_filtered = sp.remove_outliers_all(hrv)
    hrv_5m = sp.extract_segment(hrv_filtered)

    plt.close('all')
    vis.plot_RR(hrv)
    plt.savefig('figures/rr_raw.png')

    vis.plot_RR(hrv_filtered)
    plt.savefig('figures/rr_filtered.png')

    vis.plot_HR(hrv_filtered)
    plt.savefig('figures/hr_filtered.png')

    vis.plot_RR(hrv_5m)
    plt.savefig('figures/rr_5min.png')

    vis.plot_HR(hrv_5m)
    plt.savefig('figures/hr_5min.png')
    plt.show()

if __name__ == '__main__':
    plot_all()
